
const TEST_GRID = [
  [
    {},
    {},
    {},
    {
      sex: "Female",
      color: "Yellow",
      age: 0,
      name: "erica",
      is_radioactive: false,
      x: 3,
      y: 0,
      repr_age: 2,
    },
    null,
    null,
    {
      sex: "Female",
      color: "Red",
      age: 2,
      name: "casey",
      is_radioactive: false,
      x: 6,
      y: 0,
      repr_age: 2,
    },
    null,
    {
      sex: "Female",
      color: "Red",
      age: 0,
      name: "amber",
      is_radioactive: false,
      x: 8,
      y: 0,
      repr_age: 2,
    },
    {
      sex: "Female",
      color: "White",
      age: 0,
      name: "fiona",
      is_radioactive: false,
      x: 9,
      y: 0,
      repr_age: 2,
    },
  ],
  [
    {},
    {},
    {
      sex: "Male",
      color: "Magenta",
      age: 2,
      name: " Hal ",
      is_radioactive: false,
      x: 2,
      y: 1,
      repr_age: 2,
    },
    {
      sex: "Female",
      color: "Yellow",
      age: 2,
      name: "susie",
      is_radioactive: false,
      x: 3,
      y: 1,
      repr_age: 2,
    },
    {
      sex: "Female",
      color: "Yellow",
      age: 0,
      name: "sarah",
      is_radioactive: false,
      x: 4,
      y: 1,
      repr_age: 2,
    },
    null,
    {
      sex: "Female",
      color: "Red",
      age: 0,
      name: "amber",
      is_radioactive: false,
      x: 6,
      y: 1,
      repr_age: 2,
    },
    null,
    {
      sex: "Male",
      color: "Red",
      age: 0,
      name: " Wes ",
      is_radioactive: false,
      x: 8,
      y: 1,
      repr_age: 2,
    },
    {
      sex: "Female",
      color: "White",
      age: 2,
      name: "elsie",
      is_radioactive: false,
      x: 9,
      y: 1,
      repr_age: 2,
    },
  ],
  [
    {},
    {},
    {
      sex: "Male",
      color: "Yellow",
      age: 0,
      name: " Eli ",
      is_radioactive: false,
      x: 2,
      y: 2,
      repr_age: 2,
    },
    null,
    {
      sex: "Female",
      color: "Yellow",
      age: 0,
      name: "avery",
      is_radioactive: false,
      x: 4,
      y: 2,
      repr_age: 2,
    },
    null,
    {},
    {},
    null,
    {
      sex: "Female",
      color: "White",
      age: 0,
      name: "grace",
      is_radioactive: false,
      x: 9,
      y: 2,
      repr_age: 2,
    },
  ],
  [
    {
      sex: "Male",
      color: "Yellow",
      age: 0,
      name: " Zak ",
      is_radioactive: false,
      x: 0,
      y: 3,
      repr_age: 2,
    },
    null,
    {},
    null,
    {},
    {},
    {
      sex: "Female",
      color: "Cyan",
      age: 0,
      name: "riley",
      is_radioactive: false,
      x: 6,
      y: 3,
      repr_age: 2,
    },
    {
      sex: "Female",
      color: "Cyan",
      age: 2,
      name: "amber",
      is_radioactive: false,
      x: 7,
      y: 3,
      repr_age: 2,
    },
    {
      sex: "Female",
      color: "White",
      age: 0,
      name: "fiona",
      is_radioactive: false,
      x: 8,
      y: 3,
      repr_age: 2,
    },
    null,
  ],
  [
    {
      sex: "Male",
      color: "Yellow",
      age: 0,
      name: " Zak ",
      is_radioactive: false,
      x: 0,
      y: 4,
      repr_age: 2,
    },
    null,
    null,
    {
      sex: "Male",
      color: "White",
      age: 2,
      name: " Wes ",
      is_radioactive: false,
      x: 3,
      y: 4,
      repr_age: 2,
    },
    {},
    {},
    {},
    null,
    null,
    {
      sex: "Female",
      color: "Cyan",
      age: 0,
      name: "maria",
      is_radioactive: false,
      x: 9,
      y: 4,
      repr_age: 2,
    },
  ],
  [
    {},
    {
      sex: "Female",
      color: "Yellow",
      age: 2,
      name: "fiona",
      is_radioactive: false,
      x: 1,
      y: 5,
      repr_age: 2,
    },
    {},
    null,
    {},
    {},
    {},
    {
      sex: "Female",
      color: "Cyan",
      age: 0,
      name: "maria",
      repr_age: 2,
    },
    null,
    null,
  ],
  [null, {}, {}, null, {}, {}, {}, {}, {}, {}],
  [null, {}, {}, {}, null, {}, {}, {}, {}, {}],
  [
    {},
    {
      sex: "Male",
      color: "Red",
      age: 2,
      name: " Abe ",
      is_radioactive: true,
      x: 1,
      y: 8,
      repr_age: 2,
    },
    null,
    null,
    {},
    {
      sex: "Female",
      color: "White",
      age: 2,
      name: "erica",
      is_radioactive: true,
      x: 5,
      y: 8,
      repr_age: 2,
    },
    {},
    {},
    {},
    {},
  ],
  [
    {
      sex: "Male",
      color: "White",
      age: 2,
      name: " Ben ",
      is_radioactive: true,
      x: 0,
      y: 9,
      repr_age: 2,
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
  ],
];

export default TEST_GRID;
